### ISSUE TITLE
melodic is not in ros index

### ISSUE THREAD

**Issue by jwhendy** [ros-melodic-arch/ros-melodic-image-pipeline#4]
Just noticed that when I ran my script, it pulled version 1.12.16 from [ros index](http://rosindex.github.io/p/image_pipeline/), perhaps because they don't have a melodic entry yet. Just posting this here so we know there is a discrepancy which could prevent auto-updating via an official index/distro source.

I'll come back to this, likely posting to image-pipeline that they update their rosdistro .yaml entries.

**Comment by acxz** [comment]
I think it would be appropriate we move this issue to the official `image-pipeline` repo. Or this issue can be moved to the repo where you have your auto-updating script as a reminder. I do not think it falls under here.

**Comment by acxz** [comment]
Closing this with the following PR: https://github.com/ros/rosdistro/pull/23503
